// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqvJcWljVKmaO1_vX_6NYwUsEV9iMdDwA',
    appId: '1:350417486760:web:3a70c8842888aeb829d39d',
    messagingSenderId: '350417486760',
    projectId: 'inventoryapp2897',
    authDomain: 'inventoryapp2897.firebaseapp.com',
    storageBucket: 'inventoryapp2897.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyI0SVcSrMvpRNmtI-wXCELnoUoFAPqcY',
    appId: '1:350417486760:android:d30833dfd3d5b99529d39d',
    messagingSenderId: '350417486760',
    projectId: 'inventoryapp2897',
    storageBucket: 'inventoryapp2897.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj2DMQJOw8BRdR8Ia2bP5DjNMKCsxBPUg',
    appId: '1:350417486760:ios:a24dbdc09b0c4a8129d39d',
    messagingSenderId: '350417486760',
    projectId: 'inventoryapp2897',
    storageBucket: 'inventoryapp2897.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj2DMQJOw8BRdR8Ia2bP5DjNMKCsxBPUg',
    appId: '1:350417486760:ios:a24dbdc09b0c4a8129d39d',
    messagingSenderId: '350417486760',
    projectId: 'inventoryapp2897',
    storageBucket: 'inventoryapp2897.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqvJcWljVKmaO1_vX_6NYwUsEV9iMdDwA',
    appId: '1:350417486760:web:09cad783ad6a6a6329d39d',
    messagingSenderId: '350417486760',
    projectId: 'inventoryapp2897',
    authDomain: 'inventoryapp2897.firebaseapp.com',
    storageBucket: 'inventoryapp2897.firebasestorage.app',
  );
}
